### ISSUE TITLE
Implement ranges for property pixel values

### ISSUE THREAD

**Issue by ovidiubute** [ovidiubute/scry-css#28]
Given the following properties:

``` css
.class-a {
  margin-left: 23px;
  top: 45px;
}

.class-b {
  margin-left: 24px;
  top: 46px;
}

.class-c {
  margin-left: 25px;
  top: 47px;
}
```

And a LESS candidate file:

``` css
@app-margin-left: 1px;
@app-top: 2px;
```

Running the CLI you'll get the suggested variables every single time, and you may not even care because the pixel difference is pretty significant.

Proposed solution is to implement a pixel range where suggestions will only be provided given the variable values are within a range defined by the user (probably by CLI argument though a local config file would be preferable).

Note that this issue cannot be started until #3 is finished, only then can we check for the value too during the candidate discovery phase.
