### ISSUE TITLE
Basic support for LESS mixins

### ISSUE THREAD

**Issue by ovidiubute** [ovidiubute/scry-css#6]
### Need

``` gherkin
As a developer
I'd like to know if the CSS I've written can be replaced by a mixin call
So that I reuse existing functionality and increase code quality
```
### Deliverables

Mixin definitions suggested along with variables, for LESS at first (maybe SASS can be done at the same time but I'm not familiar with mixins).
### Notes

For the first iteration, simple mixin replacements should be delivered. Consider the following case:

``` CSS
.my-component {
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
}
```

Somewhere in your project:

``` CSS
.stretch() {
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
}
```

`stretch` should be a candidate mixin in this case. Only if all CSS properties with the same values are contained within a mixin should it become a candidate.

Mixin arguments are beyond the scope of the first iteration.
